name: Nuclear Option - Delete ALL Branches

on:
  workflow_dispatch:  # Only allow manual triggering for safety

jobs:
  nuke-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Wait 20 seconds
        run: |
          echo "💣 Nuclear countdown started (20s)..."
          sleep 20

      - name: Delete ALL branches
        run: |
          echo "🔥 Preparing to delete ALL branches including develop/main..."
          
          # Temporarily rename default branch to allow deletion
          git checkout develop
          git branch -m develop temporary-hold-branch
          git push origin temporary-hold-branch
          
          # Delete main branch
          git push origin --delete main || echo "⚠️ main deletion failed"
          
          # Delete original develop
          git push origin --delete develop || echo "⚠️ develop deletion failed"
          
          # Restore default branch
          git push origin temporary-hold-branch:develop
          git branch -m temporary-hold-branch develop
          
          echo "💀 All branches deleted. Default branch recreated as empty."