name: 💣 Delete All Remote Branches Except Develop

on:
  push:
    branches:
      - temp         # Trigger from temp branch
      - develop 
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Wait 20 seconds (optional)
        run: |
          echo "⏳ Waiting 20 seconds before deletion..."
          sleep 20

      - name: Set up Git
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@example.com"

      - name: Delete all remote branches except 'develop'
        run: |
          echo "🔥 Fetching all remote branches..."
          git fetch --all

          echo "🧨 Deleting all branches except 'develop'..."
          for branch in $(git branch -r | grep origin/ | sed 's/origin\///'); do
